"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# ==============================================================================
# 1. CAMINHOS BASE
# ==============================================================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# 2. SEGURANÇA (DEV)
# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2#h1*u(9y)!*j%33_p_p!lljxdl%%+8_8t4cib3wh)5ymq0f!o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# 'dpcb00.pythonanywhere.com'


# ==============================================================================
# 3. APLICAÇÕES INSTALADAS
# ==============================================================================
INSTALLED_APPS = [
    # "unfold",
    "unfold.contrib.filters",  # (Opcional) Adicione se quiser filtros bonitos
    "unfold.contrib.forms",  # (Opcional) Adicione se quiser formulários bonitos
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Bibliotecas de Terceiros
    'django.contrib.humanize', # Para formatar valores no template
    
    # Seus Apps
    'cadastro',
]

# --- CONTROLE DE SESSÃO ---
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


# ==============================================================================
# 4. TEMPLATES (HTML)
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================================================
# 5. BANCO DE DADOS
# ==============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================================================================
# 6. VALIDAÇÃO DE SENHA
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# 7. INTERNACIONALIZAÇÃO
# ==============================================================================
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 8. ARQUIVOS ESTÁTICOS E MÍDIA (CSS, JS, IMAGENS)
# ==============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Onde o Django vai procurar os arquivos estáticos durante o desenvolvimento
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# --- CONFIGURAÇÃO DE MÍDIA (UPLOADS/LOGOS) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================================================================
# 9. LOGIN E REDIRECIONAMENTO
# ==============================================================================
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Configuração padrão para chaves primárias (evita warnings)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# 10. CONFIGURAÇÃO DE E-MAIL (RECUPERAÇÃO DE SENHA)
# ==============================================================================
# Backend de CONSOLE: Imprime o e-mail no terminal preto do VS Code
# Isso é perfeito para testar sem precisar de servidor SMTP real agora.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Quando for para produção (internet), você mudará para SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# --- CONFIGURAÇÃO DO VISUAL (UNFOLD) ---
UNFOLD = {
    "SITE_TITLE": "Sistema Despachante",
    "SITE_HEADER": "Painel de Gestão",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Gestão Operacional",
                "separator": True,
                "items": [
                    {
                        "title": "Clientes",
                        "icon": "person",
                        "link": reverse_lazy("admin:cadastro_cliente_changelist"),
                    },
                    {
                        "title": "Veículos",
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:cadastro_veiculo_changelist"),
                    },
                    {
                        "title": "Atendimentos",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:cadastro_atendimento_changelist"),
                    },
                ],
            },
            {
                "title": "Administração do Sistema",
                "separator": True,
                "collapse": True,
                "items": [
                    {
                        "title": "Usuários e Acessos",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Despachantes (Empresas)",
                        "icon": "domain",
                        "link": reverse_lazy("admin:cadastro_despachante_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}

# Configuração de Cache (Memória Local - Ideal para Dev e Servidores Simples)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake', # Um nome único para sua instância
    }
}