# Generated by Django 6.0 on 2025-12-23 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despachante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('codigo_sindego', models.CharField(max_length=50, verbose_name='Código SINDEGO')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco_completo', models.TextField(help_text='Endereço que aparecerá nos requerimentos')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Goiânia', max_length=100)),
                ('uf', models.CharField(default='GO', max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_fazer_upload', models.BooleanField(default=False)),
                ('ver_financeiro', models.BooleanField(default=False)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERAR', 'Operador')], default='OPERAR', max_length=10)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='cadastro.despachante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
