# Generated by Django 6.0 on 2026-01-14 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despachante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('codigo_sindego', models.CharField(max_length=50, verbose_name='Código SINDEGO')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('endereco_completo', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, help_text='Formato obrigatório: PNG com fundo transparente. Tamanho ideal: 300x100px.', null=True, upload_to='logos_despachantes/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='Logo do Escritório')),
                ('aliquota_imposto', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de imposto sobre honorários (ex: 5.00 para 5%)', max_digits=5)),
                ('taxa_bancaria_padrao', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa bancária/maquininha média (ex: 2.50 para 2.5%)', max_digits=5)),
                ('valor_honorario_padrao', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor sugerido automaticamente no campo de honorários ao criar um novo orçamento.', max_digits=10, verbose_name='Honorário Padrão (Orçamento)')),
                ('valor_taxa_sindego_padrao', models.DecimalField(decimal_places=2, default=13.0, help_text='Valor cobrado na maioria dos processos (Custo Operacional).', max_digits=10, verbose_name='Taxa Sindego (Padrão)')),
                ('valor_taxa_sindego_reduzida', models.DecimalField(decimal_places=2, default=6.5, help_text='Valor cobrado em processos específicos.', max_digits=10, verbose_name='Taxa Sindego (Reduzida)')),
                ('email_fatura', models.EmailField(blank=True, help_text='E-mail que receberá os boletos/Pix da mensalidade do sistema.', max_length=254, null=True)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=100.0, help_text='Valor da assinatura mensal deste despachante.', max_digits=10)),
                ('dia_vencimento', models.IntegerField(choices=[(1, 'Dia 1'), (2, 'Dia 2'), (3, 'Dia 3'), (4, 'Dia 4'), (5, 'Dia 5'), (6, 'Dia 6'), (7, 'Dia 7'), (8, 'Dia 8'), (9, 'Dia 9'), (10, 'Dia 10'), (11, 'Dia 11'), (12, 'Dia 12'), (13, 'Dia 13'), (14, 'Dia 14'), (15, 'Dia 15'), (16, 'Dia 16'), (17, 'Dia 17'), (18, 'Dia 18'), (19, 'Dia 19'), (20, 'Dia 20'), (21, 'Dia 21'), (22, 'Dia 22'), (23, 'Dia 23'), (24, 'Dia 24'), (25, 'Dia 25'), (26, 'Dia 26'), (27, 'Dia 27'), (28, 'Dia 28')], default=10, verbose_name='Dia de Vencimento Preferencial')),
                ('asaas_customer_id', models.CharField(blank=True, help_text='ID gerado automaticamente pela integração.', max_length=50, null=True, verbose_name='ID Asaas (Cliente)')),
                ('asaas_api_key', models.CharField(blank=True, help_text='Chave gerada no painel do Asaas para receber pagamentos diretamente.', max_length=255, null=True, verbose_name='Chave de API (Asaas)')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=18)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20, null=True)),
                ('uf_rg', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('filiacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação (Mãe/Pai)')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Goiânia', max_length=100)),
                ('uf', models.CharField(default='GO', max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_atendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('token_rastreio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('servico', models.CharField(help_text='Nome gravado no momento do atendimento. Não muda se o catálogo mudar.', max_length=100, verbose_name='Nome do Serviço (No Processo)')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente (Com Pendência)'), ('APROVADO', 'Aprovado/Concluído'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('motivo_pendencia', models.TextField(blank=True, help_text='Descreva o que falta para o processo andar (Ex: Falta assinatura, CNH vencida).', null=True, verbose_name='Motivo da Pendência')),
                ('valor_taxas_detran', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_honorarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quem_pagou_detran', models.CharField(choices=[('DESPACHANTE', 'Escritório Pagou (Reembolsável)'), ('CLIENTE', 'Cliente Pagou por Fora')], default='DESPACHANTE', max_length=20)),
                ('custo_impostos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_taxa_bancaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_taxa_sindego', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status_financeiro', models.CharField(choices=[('ABERTO', 'Aguardando Pagamento'), ('PAGO', 'Totalmente Pago')], default='ABERTO', max_length=15)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('asaas_id', models.CharField(blank=True, help_text='ID gerado automaticamente (ex: pay_58694038593)', max_length=255, null=True, unique=True, verbose_name='ID Cobrança Asaas')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('LOGIN', 'Login'), ('FINANCEIRO', 'Financeiro'), ('STATUS', 'Mudança de Status')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cadastro.atendimento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente_avulso', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado (Gerou Processo)'), ('CANCELADO', 'Cancelado/Recusado')], default='PENDENTE', max_length=20)),
                ('valor_honorarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Honorários Totais')),
                ('valor_taxas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Soma das Taxas')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Taxa')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_fazer_upload', models.BooleanField(default=False)),
                ('ver_financeiro', models.BooleanField(default=False)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERAR', 'Operador')], default='OPERAR', max_length=10)),
                ('data_expiracao', models.DateField(blank=True, help_text='Data limite para acesso ao sistema. Deixe em branco para acesso vitalício.', null=True)),
                ('ultimo_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='cadastro.despachante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo DETRAN')),
                ('honorarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro/Honorários')),
                ('usa_taxa_sindego_reduzida', models.BooleanField(default=False, help_text='Marque se este serviço paga a taxa menor (Ex: R$ 6,50) em vez da cheia (Ex: R$ 13,00).', verbose_name='Usa Taxa Reduzida (Sindego)?')),
                ('isenta_taxa_sindego', models.BooleanField(default=False, help_text='Se marcado, o valor da taxa sindical será R$ 0,00.', verbose_name='Isento de Taxa Sindical?')),
                ('ativo', models.BooleanField(default=True)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, help_text='Selecione do catálogo para preencher valores automaticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tiposervico', verbose_name='Tipo de Serviço (Catálogo)'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('renavam', models.CharField(blank=True, max_length=11, null=True)),
                ('chassi', models.CharField(blank=True, max_length=17, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=30)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('ano_modelo', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('REBOQUE', 'Reboque')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.veiculo'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.veiculo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['despachante', 'nome'], name='cadastro_cl_despach_8df87f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['despachante', 'cpf_cnpj'], name='cadastro_cl_despach_490cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['despachante', 'data'], name='cadastro_lo_despach_c8cb44_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['atendimento'], name='cadastro_lo_atendim_2ab660_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['despachante', 'placa'], name='cadastro_ve_despach_3a5bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['cliente'], name='cadastro_ve_cliente_3d76a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='veiculo',
            unique_together={('despachante', 'placa')},
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['despachante', 'status'], name='cadastro_or_despach_3a6700_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'status'], name='cadastro_at_despach_93f75a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'data_solicitacao'], name='cadastro_at_despach_fabd89_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'status_financeiro'], name='cadastro_at_despach_e43dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['tipo_servico'], name='cadastro_at_tipo_se_e1947b_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['veiculo'], name='cadastro_at_veiculo_f47843_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['token_rastreio'], name='cadastro_at_token_r_ca9699_idx'),
        ),
    ]
