# Generated by Django 6.0 on 2025-12-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('renavam', models.CharField(blank=True, max_length=11, null=True)),
                ('chassi', models.CharField(blank=True, max_length=17, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=30)),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.PositiveIntegerField(verbose_name='Ano do Modelo')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('REBOQUE', 'Reboque')], default='CARRO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_atendimento', models.CharField(max_length=50, verbose_name='Nº de Atendimento DETRAN')),
                ('servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_ultima_consulta', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.veiculo')),
            ],
        ),
    ]
