# Generated by Django 6.0 on 2026-01-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Como resolver crítica de Chassi não confere', max_length=200)),
                ('conteudo', models.TextField(help_text='A resposta exata e técnica que a IA deve basear-se.')),
                ('categoria', models.CharField(choices=[('CRITICA', 'Resolução de Críticas/Erros'), ('PROCEDIMENTO', 'Procedimento Detran'), ('DOCUMENTACAO', 'Documentação Necessária'), ('GERAL', 'Assuntos Gerais')], default='GERAL', max_length=20)),
                ('palavras_chave', models.CharField(blank=True, help_text='Ex: chassi, remarcação, vistoria, erro 404', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual do Detran (IA)',
                'verbose_name_plural': 'Manual do Detran (IA)',
            },
        ),
    ]
