# Generated by Django 6.0 on 2026-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_baseconhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Proprietário (Doc)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Proprietário'),
        ),
    ]
