# Generated by Django 6.0 on 2025-12-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_veiculo_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='numero_atendimento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='despachante',
            name='endereco_completo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMINHAO', 'Caminhão'), ('REBOQUE', 'Reboque')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='veiculo',
            unique_together={('despachante', 'placa')},
        ),
    ]
