# Generated by Django 6.0 on 2025-12-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_atendimento_numero_atendimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='data_ultima_consulta',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='numero_atendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
    ]
