# Generated by Django 6.0 on 2026-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_veiculo_proprietario_cpf_veiculo_proprietario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachante',
            name='plano',
            field=models.CharField(choices=[('BASICO', 'Básico (Cadastros + Orçamentos)'), ('MEDIO', 'Médio (Financeiro + Boletos)'), ('PREMIUM', 'Premium (IA + Tudo)')], default='BASICO', help_text='Define quais módulos este escritório pode acessar.', max_length=20),
        ),
    ]
