# Generated by Django 6.0 on 2026-01-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_despachante_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='despachante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='cadastro.despachante'),
        ),
    ]
