# Generated by Django 6.0 on 2025-12-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_atendimento_data_ultima_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo DETRAN')),
                ('honorarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro/Honorários')),
                ('ativo', models.BooleanField(default=True)),
                ('despachante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.despachante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.veiculo')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.orcamento')),
                ('tipo_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tiposervico')),
            ],
        ),
    ]
