# Generated by Django 6.0 on 2025-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_orcamento_tiposervico_itemorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
    ]
