# Generated by Django 6.0 on 2026-01-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_perfilusuario_despachante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='data_expiracao',
        ),
        migrations.AddField(
            model_name='despachante',
            name='data_validade_sistema',
            field=models.DateField(blank=True, help_text='Se vazio, o acesso é vitalício/ilimitado.', null=True, verbose_name='Validade da Assinatura'),
        ),
    ]
