# Generated by Django 6.0 on 2026-01-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_perfilusuario_data_expiracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='precisa_mudar_senha',
            field=models.BooleanField(default=True, verbose_name='Forçar troca de senha'),
        ),
    ]
