# Generated by Django 6.0 on 2025-12-28 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_atendimento_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='nome_cliente_avulso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado (Gerou Processo)'), ('CANCELADO', 'Cancelado/Recusado')], default='PENDENTE', max_length=20),
        ),
    ]
