# Generated by Django 6.0 on 2025-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_orcamento_nome_cliente_avulso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorcamento',
            old_name='valor_cobrado',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='itemorcamento',
            name='tipo_servico',
        ),
        migrations.RemoveField(
            model_name='itemorcamento',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='servico_nome',
            field=models.CharField(default='Serviço Diverso', max_length=200),
            preserve_default=False,
        ),
    ]
