# Generated by Django 6.0 on 2025-12-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_rename_valor_cobrado_itemorcamento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='filiacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filiação (Mãe/Pai)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf_rg',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do RG'),
        ),
    ]
