# Generated by Django 6.0 on 2025-12-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_cliente_filiacao_cliente_uf_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='data_expiracao',
            field=models.DateField(blank=True, help_text='Data limite para acesso ao sistema. Deixe em branco para acesso vitalício.', null=True),
        ),
    ]
