# Generated by Django 6.0 on 2025-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_perfilusuario_data_expiracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachante',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID gerado automaticamente pela integração.', max_length=50, null=True, verbose_name='ID Asaas'),
        ),
        migrations.AddField(
            model_name='despachante',
            name='email_fatura',
            field=models.EmailField(blank=True, help_text='E-mail que receberá os boletos/Pix da mensalidade.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='despachante',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Valor da assinatura mensal deste despachante.', max_digits=10),
        ),
    ]
