# Generated by Django 6.0 on 2026-01-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_despachante_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
