# Generated by Django 6.0 on 2026-01-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_perfilusuario_ultimo_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(db_index=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
