# Generated by Django 6.0 on 2026-01-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_cliente_cpf_cnpj_alter_cliente_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico'),
        ),
    ]
