# Generated by Django 6.0 on 2026-01-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_despachante_dia_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.veiculo'),
        ),
    ]
