# Generated by Django 6.0 on 2026-01-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_alter_atendimento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.veiculo'),
        ),
    ]
