# Generated by Django 6.0 on 2026-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_orcamento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='custo_impostos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: ISS, Nota Fiscal', max_digits=10),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='custo_taxa_bancaria',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: Taxa de Cartão, Boleto ou PIX', max_digits=10),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='quem_pagou_detran',
            field=models.CharField(choices=[('DESPACHANTE', 'Escritório Pagou'), ('CLIENTE', 'Cliente Pagou por Fora')], default='DESPACHANTE', max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status_financeiro',
            field=models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PARCIAL', 'Pago Parcial'), ('PAGO', 'Totalmente Pago')], default='ABERTO', max_length=15),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='valor_honorarios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='valor_taxas_detran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
