# Generated by Django 6.0 on 2026-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_atendimento_custo_impostos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachante',
            name='aliquota_imposto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de imposto (ex: 5.00 para 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='despachante',
            name='taxa_bancaria_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa bancária/maquininha (ex: 2.50 para 2.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='custo_impostos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='custo_taxa_bancaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='quem_pagou_detran',
            field=models.CharField(choices=[('DESPACHANTE', 'Escritório Pagou (Reembolsável)'), ('CLIENTE', 'Cliente Pagou por Fora')], default='DESPACHANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado/Concluído'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status_financeiro',
            field=models.CharField(choices=[('ABERTO', 'Aguardando Pagamento'), ('PAGO', 'Totalmente Pago')], default='ABERTO', max_length=15),
        ),
    ]
