# Generated by Django 6.0 on 2026-01-10 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_despachante_aliquota_imposto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachante',
            name='logo',
            field=models.ImageField(blank=True, help_text='Formato obrigatório: PNG com fundo transparente. Tamanho ideal: 300x100px.', null=True, upload_to='logos_despachantes/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='Logo do Escritório'),
        ),
    ]
