# Generated by Django 6.0 on 2026-01-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_logatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='custo_taxa_sindego',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='despachante',
            name='valor_taxa_sindego_padrao',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Valor cobrado na maioria dos processos.', max_digits=10, verbose_name='Taxa Sindego (Padrão)'),
        ),
        migrations.AddField(
            model_name='despachante',
            name='valor_taxa_sindego_reduzida',
            field=models.DecimalField(decimal_places=2, default=6.5, help_text='Valor cobrado em processos específicos.', max_digits=10, verbose_name='Taxa Sindego (Reduzida)'),
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='usa_taxa_sindego_reduzida',
            field=models.BooleanField(default=False, help_text='Marque se este serviço paga a taxa menor (Ex: R$ 6,50) em vez da cheia (Ex: R$ 13,00).', verbose_name='Usa Taxa Reduzida (Sindego)?'),
        ),
    ]
