# Generated by Django 6.0 on 2026-01-12 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_atendimento_custo_taxa_sindego_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'status'], name='cadastro_at_despach_93f75a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'data_solicitacao'], name='cadastro_at_despach_fabd89_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['despachante', 'status_financeiro'], name='cadastro_at_despach_e43dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['veiculo'], name='cadastro_at_veiculo_f47843_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['despachante', 'nome'], name='cadastro_cl_despach_8df87f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['despachante', 'cpf_cnpj'], name='cadastro_cl_despach_490cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['despachante', 'data'], name='cadastro_lo_despach_c8cb44_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['atendimento'], name='cadastro_lo_atendim_2ab660_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['despachante', 'status'], name='cadastro_or_despach_3a6700_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['despachante', 'placa'], name='cadastro_ve_despach_3a5bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['cliente'], name='cadastro_ve_cliente_3d76a9_idx'),
        ),
    ]
