# Generated by Django 6.0 on 2026-01-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_alter_atendimento_options_alter_cliente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, help_text='Selecione do catálogo para preencher valores automaticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tiposervico', verbose_name='Tipo de Serviço (Catálogo)'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.CharField(help_text='Nome gravado no momento do atendimento. Não muda se o catálogo mudar.', max_length=100, verbose_name='Nome do Serviço (No Processo)'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['tipo_servico'], name='cadastro_at_tipo_se_e1947b_idx'),
        ),
    ]
