# Generated by Django 6.0 on 2026-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_atendimento_tipo_servico_alter_atendimento_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='asaas_id',
            field=models.CharField(blank=True, help_text='ID gerado automaticamente (ex: pay_58694038593)', max_length=255, null=True, unique=True, verbose_name='ID Cobrança Asaas'),
        ),
    ]
