# Generated by Django 6.0 on 2026-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_atendimento_asaas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachante',
            name='asaas_api_key',
            field=models.CharField(blank=True, help_text='Chave gerada no painel do Asaas para receber pagamentos diretamente.', max_length=255, null=True, verbose_name='Chave de API (Asaas)'),
        ),
        migrations.AlterField(
            model_name='despachante',
            name='asaas_customer_id',
            field=models.CharField(blank=True, help_text='ID gerado automaticamente pela integração.', max_length=50, null=True, verbose_name='ID Asaas (Cliente)'),
        ),
    ]
