# Generated by Django 6.0 on 2026-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_despachante_asaas_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='valor_honorario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Honorários (Lucro)'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxas (Estado)'),
        ),
    ]
