# Generated by Django 6.0 on 2026-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_itemorcamento_valor_honorario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='isenta_taxa_sindego',
            field=models.BooleanField(default=False, help_text='Se marcado, o valor da taxa sindical será R$ 0,00.', verbose_name='Isento de Taxa Sindical?'),
        ),
    ]
