# Generated by Django 6.0 on 2026-01-14 19:17

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0029_cliente_data_nascimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='motivo_pendencia',
            field=models.TextField(blank=True, help_text='Descreva o que falta para o processo andar (Ex: Falta assinatura, CNH vencida).', null=True, verbose_name='Motivo da Pendência'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='token_rastreio',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('PENDENTE', 'Pendente (Com Pendência)'), ('APROVADO', 'Aprovado/Concluído'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['token_rastreio'], name='cadastro_at_token_r_ca9699_idx'),
        ),
    ]
