# Generated by Django 6.0 on 2026-01-14 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_atendimento_motivo_pendencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='token_rastreio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
